#!/usr/bin/env bash
# skills/rdd-quick/scripts/scaffold_plan.sh
# Generate .rddf/plans/quick-<name>.md from a proposal text.
# TDD 5-marker skeleton + ## Acceptance section. Stdlib only.
#
# Usage:
#   scaffold_plan.sh --name <kebab-case> [--proposal "<text>"] [< /dev/stdin]
#   scaffold_plan.sh --help
#
# Environment:
#   RDDF_QUICK_PLAN_DIR  default ".rddf/plans" (override for test isolation)
set -euo pipefail

NAME=""
PROPOSAL_TEXT=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --name)
            NAME="${2:-}"
            shift 2
            ;;
        --proposal)
            PROPOSAL_TEXT="${2:-}"
            shift 2
            ;;
        --help|-h)
            cat <<'EOF'
Usage: scaffold_plan.sh --name <kebab-case> [--proposal "<text>"]

Generates a TDD 5-marker skeleton + ## Acceptance section to
${RDDF_QUICK_PLAN_DIR:-.rddf/plans}/quick-<name>.md.

Refuses to overwrite an existing target. Reads proposal from --proposal
flag or stdin.
EOF
            exit 0
            ;;
        *)
            echo "ERROR: unknown argument: $1" >&2
            exit 2
            ;;
    esac
done

if [[ -z "$NAME" ]]; then
    echo "ERROR: --name required" >&2
    exit 2
fi

if ! [[ "$NAME" =~ ^[a-z0-9]+(-[a-z0-9]+)*$ ]]; then
    echo "ERROR: --name must be kebab-case (got: $NAME)" >&2
    exit 2
fi

# Read proposal from stdin if not provided via flag.
if [[ -z "$PROPOSAL_TEXT" ]]; then
    PROPOSAL_TEXT="$(cat)"
fi

PLAN_DIR="${RDDF_QUICK_PLAN_DIR:-.rddf/plans}"
OUT_FILE="${PLAN_DIR}/quick-${NAME}.md"

if [[ -e "$OUT_FILE" ]]; then
    echo "ERROR: $OUT_FILE already exists; refusing to overwrite" >&2
    exit 1
fi

mkdir -p "$PLAN_DIR"

# Pass data via env vars (no shell string interpolation per Oracle C1).
export RDDF_QS_NAME="$NAME"
export RDDF_QS_PROPOSAL="$PROPOSAL_TEXT"
export RDDF_QS_OUT="$OUT_FILE"

python3 - <<'PYEOF'
import os
from pathlib import Path

name = os.environ["RDDF_QS_NAME"]
proposal = os.environ["RDDF_QS_PROPOSAL"]
out_path = os.environ["RDDF_QS_OUT"]

# Safe because RDDF_QS_OUT was set by us and OUT_FILE existence was already
# checked; no untrusted data flows into this path component here.
template = f"""# quick-{name}

> **Generated by rdd-quick scaffold_plan.sh** — fill in concrete content under each TDD step.

**Goal**: {proposal}

**Architecture**: (fill in — one paragraph describing the approach)

**Tech Stack**: (fill in — languages, frameworks, key libraries)

---

### Task 1: (component name)

**Files:**
- Create: `path/to/new_file.py`
- Modify: `path/to/existing.py`
- Test: `tests/path/test_x.py`

- [ ] **Step 1: Write the failing test**
- [ ] **Step 2: Run test to verify it fails**
- [ ] **Step 3: Write minimal implementation**
- [ ] **Step 4: Run test to verify it passes**
- [ ] **Step 5: Defer commit**

## Acceptance

- [ ] AC-1: (description — concrete, verifiable in one command)
- [ ] AC-2: (description)
- [ ] AC-3: (description)
"""

Path(out_path).write_text(template)
print(f"wrote {out_path}")
PYEOF