#!/bin/bash
# Spec Workflow 安装脚本
# 用法:
#   bash install.sh                    # 安装到当前项目 (.opencode/skills/rdd-workflow/)
#   bash install.sh /path/to/project   # 安装到指定项目
#   bash install.sh --global           # 全局安装到 ~/.agents/skills/ + Python deps + rddf CLI
#
# 全局安装后,OpenCode 在任何项目下自动发现 rdd-workflow 技能:
#   skill_use("guide")
#   skill_use("guide-arch")
#   ...

set -euo pipefail

# ── 配置 ──────────────────────────────────────────────────────────
PACKAGE_DIR="$(cd "$(dirname "$(realpath "$0" 2>/dev/null || readlink -f "$0")")" && pwd)"
AGENTS_DIR="${HOME}/.agents/skills"
LOCAL_BIN="${HOME}/.local/bin"

# 所有子技能列表（排除 _lib/ __pycache__ 等非技能目录）
SUB_SKILLS=()
for d in "$PACKAGE_DIR/skills/"*/; do
    s=$(basename "$d")
    [ "$s" = "_lib" ] && continue
    [ "$s" = "__pycache__" ] && continue
    [ "$s" = "cli" ] && continue
    [ -f "$d/SKILL.md" ] && SUB_SKILLS+=("$s")
done

# ── 辅助函数 ──────────────────────────────────────────────────────
info()  { echo -e " \033[1;34m→\033[0m $*"; }
ok()    { echo -e " \033[1;32m✅\033[0m $*"; }
warn()  { echo -e " \033[1;33m⚠️\033[0m $*" >&2; }
fail()  { echo -e " \033[1;31m❌\033[0m $*" >&2; exit 1; }

install_python_deps() {
    info "安装 Python 依赖..."
    if [ ! -f "$PACKAGE_DIR/requirements.txt" ]; then
        warn "requirements.txt 不存在，跳过"
        return
    fi
    if [ -n "${VIRTUAL_ENV:-}" ]; then
        pip3 install -r "$PACKAGE_DIR/requirements.txt" 2>&1 | sed 's/^/   /' || {
            warn "pip install 失败（部分依赖可能已存在）"
        }
    else
        pip3 install --user -r "$PACKAGE_DIR/requirements.txt" 2>&1 | sed 's/^/   /' || {
            warn "pip install 失败（部分依赖可能已存在）"
        }
    fi
    ok "Python 依赖安装完成"
}

create_pth_file() {
    info "创建 Python .pth 文件..."
    local SKILLS_PARENT SITE_PACKAGES=""
    SKILLS_PARENT="$PACKAGE_DIR"  # skills/ 的父目录（package root），from skills._lib import xxx 需要父目录在 sys.path 上

    # 检测是否在 virtualenv 中 —— .pth 必须写入可见的 site-packages
    if [ -n "${VIRTUAL_ENV:-}" ]; then
        local VENV_SITE
        VENV_SITE=$(python3 -c "import sys; print([p for p in sys.path if 'site-packages' in p][0])" 2>/dev/null) || VENV_SITE=""
        if [ -n "$VENV_SITE" ] && [ -d "$VENV_SITE" ]; then
            SITE_PACKAGES="$VENV_SITE"
        fi
    fi
    if [ -z "${SITE_PACKAGES:-}" ]; then
        SITE_PACKAGES=$(python3 -c "import site; print(site.getusersitepackages())" 2>/dev/null) || {
            warn "无法获取 site-packages 路径，跳过 .pth"
            return
        }
    fi

    mkdir -p "$SITE_PACKAGES"
    local PTH_FILE="$SITE_PACKAGES/rdd-workflow.pth"
    echo "# Spec Workflow _lib path (auto-generated by install.sh --global)" > "$PTH_FILE"
    echo "$SKILLS_PARENT" >> "$PTH_FILE"
    ok ".pth 已创建: $PTH_FILE → $SKILLS_PARENT"
}

create_rddf_symlink() {
    info "创建 rddf CLI 命令..."
    local RDDF_SRC="$PACKAGE_DIR/skills/cli/rddf.sh"
    local RDDF_TARGET="${LOCAL_BIN}/rddf"
    mkdir -p "$LOCAL_BIN"
    if [ -f "$RDDF_TARGET" ] || [ -L "$RDDF_TARGET" ]; then
        rm -f "$RDDF_TARGET"
    fi
    ln -sf "$RDDF_SRC" "$RDDF_TARGET"
    chmod +x "$RDDF_TARGET"
    ok "rddf CLI: $RDDF_TARGET → $RDDF_SRC"
    # 检查 PATH
    case ":${PATH:-}:" in
        *:"${LOCAL_BIN}":*) ;;
        *) warn "${LOCAL_BIN} 不在 PATH 中，请添加到 shell 配置: export PATH=\"${LOCAL_BIN}:\$PATH\"" ;;
    esac
}

write_orchestrator_env() {
    info "写入 RDDF_USE_ORCHESTRATOR_DEFAULT=yes 到 ~/.config/rdd-workflow/env..."
    local ENV_FILE="${HOME}/.config/rdd-workflow/env"
    mkdir -p "$(dirname "$ENV_FILE")"
    if [ ! -f "$ENV_FILE" ] || ! grep -q '^RDDF_USE_ORCHESTRATOR_DEFAULT=' "$ENV_FILE" 2>/dev/null; then
        printf '\n# RDDF_USE_ORCHESTRATOR_DEFAULT — spec 2026-08-13 §2 (orchestrator default-ON)\nexport RDDF_USE_ORCHESTRATOR_DEFAULT=yes\n' >> "$ENV_FILE"
        ok "env hook written: $ENV_FILE"
    else
        info "RDDF_USE_ORCHESTRATOR_DEFAULT 已存在，跳过"
    fi
}

install_global_symlinks() {
    echo ""
    echo "========================================="
    echo " 🌐 Spec Workflow — 全局安装"
    echo "========================================="
    echo ""

    # 1) 创建子技能 symlink
    mkdir -p "$AGENTS_DIR"
    local COUNT=0
    for skill in "${SUB_SKILLS[@]}"; do
        local src="$PACKAGE_DIR/skills/$skill"
        local dst="$AGENTS_DIR/$skill"
        if [ -L "$dst" ] || [ -d "$dst" ]; then
            rm -f "$dst"
        fi
        ln -sf "$src" "$dst"
        COUNT=$((COUNT + 1))
    done

    # Symlink _lib (shared library — not a skill, but required by all skills'
    # bash code blocks and scripts via resolve_rdd_lib_dir()). Without this,
    # globally-installed skills fail outside the rdd-workflow repo.
    local LIB_SRC="$PACKAGE_DIR/_lib"
    local LIB_DST="$AGENTS_DIR/_lib"
    if [ -L "$LIB_DST" ] || [ -d "$LIB_DST" ]; then
        rm -f "$LIB_DST"
    fi
    ln -sf "$LIB_SRC" "$LIB_DST"

    # Copy orchestrator_entry.sh and post_flow_wrap.sh from skills/_lib/
    # These are in skills/_lib/ (not top-level _lib/) and are needed by the
    # phase entry scripts for the global fallback pattern:
    #   source "${RDDF_PROJECT_ROOT:-...}/skills/_lib/orchestrator_entry.sh"
    # Without these files in ~/.agents/skills/_lib/, globally-installed skills
    # cannot source the orchestrator when invoked from third-party projects.
    if [ -f "$PACKAGE_DIR/skills/_lib/orchestrator_entry.sh" ]; then
        cp -f "$PACKAGE_DIR/skills/_lib/orchestrator_entry.sh" "$AGENTS_DIR/_lib/"
    fi
    if [ -f "$PACKAGE_DIR/skills/_lib/post_flow_wrap.sh" ]; then
        cp -f "$PACKAGE_DIR/skills/_lib/post_flow_wrap.sh" "$AGENTS_DIR/_lib/"
    fi

    # 兼容: 旧 install.sh 用户可能引用 PACKAGE_DIR=$HOME/.agents/skills/rdd-workflow，
    # 创建完整包引用让 INSTALL.md 的 $PACKAGE_DIR 解析依然有效
    local PACKAGE_SYMLINK="$AGENTS_DIR/rdd-workflow"
    if [ ! -L "$PACKAGE_SYMLINK" ] && [ ! -d "$PACKAGE_SYMLINK" ]; then
        ln -sf "$PACKAGE_DIR" "$PACKAGE_SYMLINK"
    fi

    ok "已创建 $COUNT 个子技能 symlink → $AGENTS_DIR/"
    echo ""
    echo "   技能列表:"
    for skill in "${SUB_SKILLS[@]}"; do
        echo "     • $skill"
    done

    # 2) 安装 Python 依赖
    echo ""
    install_python_deps

    # 3) 创建 .pth 文件
    create_pth_file

    # 4) 创建 rddf CLI
    create_rddf_symlink

    # 5) 验证
    echo ""
    echo "──────── 验证 ────────"
    local VERIFY_FAIL=0
    for skill in "${SUB_SKILLS[@]}"; do
        if [ -L "$AGENTS_DIR/$skill" ] && [ -f "$AGENTS_DIR/$skill/SKILL.md" ]; then
            :  # ok
        else
            warn "symlink 异常: $AGENTS_DIR/$skill"
            VERIFY_FAIL=1
        fi
    done
    if [ "$VERIFY_FAIL" = 0 ]; then
        ok "所有 symlink 有效"
    fi

    # 验证 Python import
    if python3 -c "from skills._lib import gate; print('skills._lib.gate:', gate.__file__)" 2>/dev/null; then
        ok "Python import skills._lib 成功"
    else
        warn "Python import 验证失败 → 可能需重新打开终端或手动: pip3 install --user -r $PACKAGE_DIR/requirements.txt"
    fi

    echo ""
    echo "========================================"
    echo " ✅ 全局安装完成！"
    echo "========================================"
    echo ""
    echo "  OpenCode 自动发现技能 → 在任何项目下:"
    echo "    skill_use(\"guide\")       # 推荐器入口"
    echo "    skill_use(\"guide-arch\")  # Arch 阶段"
    echo "    skill_use(\"guide-plan\")  # Plan 阶段"
    echo "    skill_use(\"guide-ship\")  # Ship 阶段"
    echo ""
    echo "  CLI 工具:"
    echo "    rddf status    # 查看工作流状态"
    echo "    rddf sessions  # 管理 session"
    echo ""
    echo "  如果需要重新加载:"
    echo "    bash $0 --global"
    echo ""
}

install_per_project() {
    local TARGET_DIR="$1"
    local SKILLS_TARGET="$TARGET_DIR/.opencode/skills/rdd-workflow"

    echo ""
    echo "========================================="
    echo " 📦 Spec Workflow — 项目安装"
    echo "    目标: $TARGET_DIR"
    echo "========================================="
    echo ""

    mkdir -p "$SKILLS_TARGET/skills"
    mkdir -p "$SKILLS_TARGET/_lib"

    # 复制子技能（.md + per-skill 子目录）
    for skill_dir in "$PACKAGE_DIR/skills/"*/; do
        skill_name=$(basename "$skill_dir")
        [ "$skill_name" = "_lib" ] && continue
        [ "$skill_name" = "__pycache__" ] && continue
        [ "$skill_name" = "cli" ] && continue
        if [ -d "$skill_dir" ]; then
            mkdir -p "$SKILLS_TARGET/skills/$skill_name/scripts" \
                     "$SKILLS_TARGET/skills/$skill_name/references"
            [ -f "$skill_dir/SKILL.md" ] && cp -f "$skill_dir/SKILL.md" "$SKILLS_TARGET/skills/$skill_name/"
            [ -f "$skill_dir/__init__.py" ] && cp -f "$skill_dir/__init__.py" "$SKILLS_TARGET/skills/$skill_name/"
            if [ -d "$skill_dir/scripts" ]; then
                cp -rf "$skill_dir/scripts/." "$SKILLS_TARGET/skills/$skill_name/scripts/"
            fi
            if [ -d "$skill_dir/references" ]; then
                cp -rf "$skill_dir/references/." "$SKILLS_TARGET/skills/$skill_name/references/"
            fi
        fi
    done
    # 顶层 INSTALL.md
    cp -f "$PACKAGE_DIR/skills/INSTALL.md" "$SKILLS_TARGET/skills/"

    # 复制 _lib/
    if [ -d "$PACKAGE_DIR/_lib" ]; then
        find "$PACKAGE_DIR/_lib" \
            -type d \( -name __pycache__ -o -name plugins -o -name schedulers \) -prune \
            -o -type f \( -name '*.py' -o -name '*.json' -o -name '*.sh' \) -print 2>/dev/null | while read -r src; do
            rel="${src#$PACKAGE_DIR/}"
            mkdir -p "$SKILLS_TARGET/$(dirname "$rel")"
            cp -f "$src" "$SKILLS_TARGET/$rel"
        done
    fi

    # package.json
    [ -f "$PACKAGE_DIR/package.json" ] && cp -f "$PACKAGE_DIR/package.json" "$SKILLS_TARGET/"

    # 安装脚本（供其他 AI 助手使用）
    cat > "$TARGET_DIR/install-rdd-workflow.sh" << 'SCRIPT'
#!/bin/bash
# Spec Workflow 安装脚本（供其他 AI 助手使用）
# 用法: bash install-rdd-workflow.sh

set -e
PACKAGE_DIR="${PACKAGE_DIR:-$HOME/.agents/skills/rdd-workflow}"
PROJECT_ROOT=$(git rev-parse --show-toplevel 2>/dev/null || pwd)

echo "📦 安装 Spec Workflow 到: $PROJECT_ROOT"

mkdir -p "$PROJECT_ROOT/.opencode/skills/rdd-workflow/skills"

if [ -d "$PACKAGE_DIR/skills" ]; then
    for skill_dir in "$PACKAGE_DIR/skills/"*/; do
        skill_name=$(basename "$skill_dir")
        [ "$skill_name" = "_lib" ] && continue
        [ "$skill_name" = "__pycache__" ] && continue
        if [ -d "$skill_dir" ]; then
            mkdir -p "$PROJECT_ROOT/.opencode/skills/rdd-workflow/skills/$skill_name/scripts" \
                     "$PROJECT_ROOT/.opencode/skills/rdd-workflow/skills/$skill_name/references"
            [ -f "$skill_dir/SKILL.md" ] && cp -f "$skill_dir/SKILL.md" "$PROJECT_ROOT/.opencode/skills/rdd-workflow/skills/$skill_name/"
        fi
    done
    cp -f "$PACKAGE_DIR/skills/INSTALL.md" "$PROJECT_ROOT/.opencode/skills/rdd-workflow/skills/"
    if [ -d "$PACKAGE_DIR/_lib" ]; then
        mkdir -p "$PROJECT_ROOT/.opencode/skills/rdd-workflow/_lib"
        cp -r "$PACKAGE_DIR/_lib/." "$PROJECT_ROOT/.opencode/skills/rdd-workflow/_lib/"
        echo "✅ _lib 已安装"
    fi
    echo "✅ 技能已安装"
    ls -1 "$PROJECT_ROOT/.opencode/skills/rdd-workflow/skills/"
else
    echo "❌ 找不到技能包: $PACKAGE_DIR/skills"
    exit 1
fi
SCRIPT
    chmod +x "$TARGET_DIR/install-rdd-workflow.sh"

    echo ""
    echo "========================================"
    echo " ✅ 安装完成！"
    echo "========================================"
    echo ""
    echo "已安装的子技能:"
    ls -1 "$SKILLS_TARGET/skills/"
    echo ""
    echo "使用方式: skill_use(\"guide\")"
    echo ""
}

# ── 主流程 ────────────────────────────────────────────────────────
case "${1:-}" in
    --global|-g)
        install_global_symlinks
        ;;
    --help|-h)
        echo "用法: bash install.sh [选项] [目标目录]"
        echo ""
        echo "选项:"
        echo "  --global, -g      全局安装到 ~/.agents/skills/ + Python deps + rddf CLI"
        echo "  --help, -h        显示此帮助"
        echo ""
        echo "不带参数: 安装到当前项目目录"
        echo "  bash install.sh /path/to/project  安装到指定项目"
        echo ""
        echo "全局安装后，在任何项目下:"
        echo "  skill_use(\"guide\")"
        echo "  rddf status"
        ;;
    *)
        TARGET_DIR="${1:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}"
        install_per_project "$TARGET_DIR"
        ;;
esac