#!/bin/bash
# deploy.sh — Idempotent Hub protocol injection for AI assistant tools
# Usage:
#   bash deploy.sh --tools cursor,cline,continue,copilot,claude
#   bash deploy.sh --tools all
#   bash deploy.sh --status
#   bash deploy.sh --uninstall --tools all

set -euo pipefail

PACKAGE_DIR="$(cd "$(dirname "$(realpath "$0" 2>/dev/null || readlink -f "$0")")" && pwd)"
SKILL_DIR="$(dirname "$PACKAGE_DIR")"
PROTOCOL_FILE="$SKILL_DIR/inject.md"
TEMPLATES_DIR="$SKILL_DIR/templates"

# Tool definitions: name → config file path (relative to project root)
declare -A TOOL_CONFIGS=(
  [cursor]=".cursorrules"
  [cline]=".clinerules"
  [continue]=".continue/rules/cross-repo-hub.md"
  [copilot]=".github/copilot-instructions.md"
  [claude]="CLAUDE.md"
)

declare -A TOOL_TEMPLATE_SUFFIXES=(
  [cursor]=".cursorrules"
  [cline]=".clinerules"
  [continue]=".rules.md"
  [copilot]=".instructions.md"
  [claude]=".CLAUDE.md"
)

info()  { echo -e " \033[1;34m→\033[0m $*"; }
ok()    { echo -e " \033[1;32m✅\033[0m $*"; }
warn()  { echo -e " \033[1;33m⚠️\033[0m $*" >&2; }
fail()  { echo -e " \033[1;31m❌\033[0m $*" >&2; exit 1; }

# Get template content for a given tool
get_template_content() {
  local tool="$1"
  local template_file="$TEMPLATES_DIR/${tool}${TOOL_TEMPLATE_SUFFIXES[$tool]}"
  if [ -f "$template_file" ]; then
    cat "$template_file"
  else
    # Fallback: generate from protocol template
    local header="# rdd-hub Cross-Repo Protocol Rules (${tool^})"
    echo "$header"
    echo ""
    echo "You are operating in a Spoke repository that participates in the rdd-hub"
    echo "Hub-and-Spoke federation. Follow these rules when interacting with the Hub."
    echo ""
    echo "## RFC Initiation"
    echo "Before creating RFC issues, check for duplicates. Respect rate limits."
    echo ""
    echo "## RFC Review"
    echo "Apply Hub feedback before proceeding. Never skip review."
    echo ""
    echo "## Sync"
    echo "Pull contract changes via hub_sync_contract. Fail fast on errors."
    echo ""
    echo "## Auto-Approval Prohibition"
    echo "Never auto-approve RFCs. Never suppress warnings. Never bypass rate limits."
  fi
}

# Check if project is a git repo
is_git_repo() {
  local target="${1:-$(pwd)}"
  [ -d "$target/.git" ] || git -C "$target" rev-parse --git-dir >/dev/null 2>&1
}

# Check if protocol block already exists in file
has_protocol_block() {
  local file="$1"
  [ -f "$file" ] && grep -q "<!-- RDD-HUB-PROTOCOL-START -->" "$file"
}

# Create backup with YYYYMMDD suffix
create_backup() {
  local file="$1"
  if [ ! -f "$file" ]; then
    return 0
  fi
  local backup="${file}.bak.$(date +%Y%m%d)"
  cp "$file" "$backup"
  echo "$backup"
}

# Inject protocol block into config file
inject_protocol() {
  local tool="$1"
  local target_dir="${2:-$(pwd)}"
  local config="${TOOL_CONFIGS[$tool]}"
  local file="$target_dir/$config"
  local tool_upper="${tool^}"

  if ! is_git_repo "$target_dir"; then
    warn "Not a git repo: $target_dir, skipping $tool"
    return 0
  fi

  # Create parent directories if needed
  local dir
  dir=$(dirname "$file")
  mkdir -p "$dir"

  # Check if already injected
  if has_protocol_block "$file"; then
    info "$tool: protocol already injected, skipping"
    return 0
  fi

  # Create backup if file exists
  if [ -f "$file" ]; then
    local backup
    backup=$(create_backup "$file")
    info "$tool: backed up to $backup"
  fi

  # Get template content
  local content
  content=$(get_template_content "$tool")

  # Build the injection block
  local block="<!-- RDD-HUB-PROTOCOL-START -->
<!-- Generated by spoke-system-prompt-injection v1.0 -->
$content
<!-- RDD-HUB-PROTOCOL-END -->"

  # Append to file
  if [ -f "$file" ]; then
    printf '\n%s\n' "$block" >> "$file"
  else
    printf '%s\n' "$block" > "$file"
  fi

  ok "$tool: injected into $file"
}

# Uninstall protocol block from config file
uninstall_protocol() {
  local tool="$1"
  local target_dir="${2:-$(pwd)}"
  local config="${TOOL_CONFIGS[$tool]}"
  local file="$target_dir/$config"

  if ! is_git_repo "$target_dir"; then
    warn "Not a git repo: $target_dir, skipping $tool"
    return 0
  fi

  if [ ! -f "$file" ]; then
    info "$tool: no config file, skipping"
    return 0
  fi

  if ! has_protocol_block "$file"; then
    info "$tool: no protocol block found, skipping"
    return 0
  fi

  # Find backup
  local backup
  backup=$(ls -t "${file}.bak."* 2>/dev/null | head -1 || true)
  if [ -n "$backup" ] && [ -f "$backup" ]; then
    cp "$backup" "$file"
    ok "$tool: restored from $backup"
  else
    # Remove the block manually
    local tmp
    tmp=$(mktemp)
    awk '/<!-- RDD-HUB-PROTOCOL-START -->/{skip=1; next} /<!-- RDD-HUB-PROTOCOL-END -->/{skip=0; next} !skip' "$file" > "$tmp"
    mv "$tmp" "$file"
    ok "$tool: removed protocol block"
  fi
}

# Show status of protocol injection
show_status() {
  local target_dir="${1:-$(pwd)}"

  echo ""
  echo "=== Spoke Protocol Status: $target_dir ==="
  echo ""

  for tool in cursor cline continue copilot claude; do
    local config="${TOOL_CONFIGS[$tool]}"
    local file="$target_dir/$config"
    local status="not installed"
    if [ -f "$file" ]; then
      if has_protocol_block "$file"; then
        status="installed"
      else
        status="file exists (no protocol)"
      fi
    fi
    printf "  %-10s %-30s %s\n" "$tool" "$config" "$status"
  done
  echo ""
}

# Parse tools argument (comma-separated or 'all')
parse_tools() {
  local input="$1"
  if [ "$input" = "all" ]; then
    echo "cursor cline continue copilot claude"
  else
    echo "$input" | tr ',' ' '
  fi
}

# Main
main() {
  local action="inject"
  local tools_arg="all"
  local target_dir="${RDDF_SPOKE_TARGET_DIR:-$(pwd)}"

  while [ $# -gt 0 ]; do
    case "$1" in
      --tools)
        tools_arg="$2"
        shift 2
        ;;
      --uninstall)
        action="uninstall"
        shift
        ;;
      --status)
        action="status"
        shift
        ;;
      --help|-h)
        echo "Usage: $0 [--tools cursor,cline,continue,copilot,claude|all] [--uninstall] [--status] [--help]"
        echo ""
        echo "Options:"
        echo "  --tools TOOLS   Comma-separated tool list or 'all' (default: all)"
        echo "  --uninstall     Remove injected protocol blocks"
        echo "  --status        Show injection status"
        echo "  --help, -h      Show this help"
        echo ""
        echo "Environment:"
        echo "  RDDF_SPOKE_TARGET_DIR   Target directory (default: cwd)"
        exit 0
        ;;
      *)
        fail "Unknown option: $1"
        ;;
    esac
  done

  case "$action" in
    status)
      show_status "$target_dir"
      ;;
    inject|uninstall)
      local tools
      tools=$(parse_tools "$tools_arg")
      for tool in $tools; do
        if [ -z "${TOOL_CONFIGS[$tool]:-}" ]; then
          warn "Unknown tool: $tool, skipping"
          continue
        fi
        if [ "$action" = "inject" ]; then
          inject_protocol "$tool" "$target_dir"
        else
          uninstall_protocol "$tool" "$target_dir"
        fi
      done
      ;;
  esac
}

main "$@"
