#!/usr/bin/env bash
# Phase 0: 4-option approval gate (HARD pause).
# Reject/defer/revise routes via rddf feedback add (single-writer contract, per ADR-0037).
# Approve triggers D3 spec-delta generation per ADR-0025 (inline Python helper, decoupled from guide-design).
set -euo pipefail

CHANGE_NAME="${1:-}"
PROJECT_ROOT="${PROJECT_ROOT:-$(pwd)}"

if [ -z "$CHANGE_NAME" ]; then
    echo "phase0_approval.sh requires <change-name>" >&2
    exit 2
fi

echo "=== Phase 0: Approval Gate for $CHANGE_NAME ==="

echo "1) approve  2) reject  3) defer  4) revise"
read -r -p "Choose [1-4]: " choice

case "$choice" in
    1)
        echo "approved"
        python3 <<PYEOF
import sys
from pathlib import Path
specs_dir = Path("$PROJECT_ROOT") / "openspec/specs/$CHANGE_NAME"
specs_dir.mkdir(parents=True, exist_ok=True)
spec_md = specs_dir / "spec.md"
if not spec_md.exists():
    spec_md.write_text("""## ADDED Requirements

### Requirement: $CHANGE_NAME
Auto-generated by rdd-builder Phase 0 approve (per ADR-0025 D3).
""")
print(f"D3 spec-delta written: {spec_md}")
PYEOF
        exit 0
        ;;
    2)
        echo "rejected"
        rddf feedback add "$CHANGE_NAME" --from rdd-builder --kind rejected --body "Rejected in Phase 0" || echo "(feedback add deferred)"
        exit 0
        ;;
    3)
        echo "deferred"
        rddf feedback add "$CHANGE_NAME" --from rdd-builder --kind blocked --body "Deferred in Phase 0" || echo "(feedback add deferred)"
        exit 0
        ;;
    4)
        echo "revising"
        rddf feedback add "$CHANGE_NAME" --from rdd-builder --kind needs-revision --body "Revision requested in Phase 0" || echo "(feedback add deferred)"
        exit 1
        ;;
    *)
        echo "invalid choice" >&2
        exit 2
        ;;
esac