# clean-stale-plan-handoff-on-ship-done — Implementation Tasks

> Auto-generated by `guide-plan` Phase 2.5 fill. Source: `proposal.md` "What Changes" section.

## Implementation Tasks

### Phase 1: Setup & TDD red

- [x] Read `proposal.md` fully (especially "What Changes" and "Acceptance Criteria" if present)
- [x] Identify all `**不**` (NOT in scope) items to AVOID
- [x] Write failing test(s) covering scenarios 场景 A (主场景) per proposal.md
- [x] Verify tests fail (red) — `pytest tests/unit/<new_test>.py` or `bats tests/integration/<new>.bats`

### Phase 2: Implementation

- [x] Task 1: 修改 skills/guide-ship/scripts/ship_archive.sh::cleanup_plan_handoff() 的 Python 块
- [x] Task 2: 新增 current_change 字段处理：当被 cleanup 的 change_name == data.get("current_change") 时设 current_change=None
- [x] Task 3: 新增 ship_started_at 字段处理：所有 changes 归档完成（active_changes==0）时设 ship_started_at=None
- [x] Task 4: 保留 execution_mode_decisions 不动（属于 ship 历史记录，对未来 ship 决策有参考价值）
- [x] Task 5: 添加最终态一致性检查（active_changes==0 ⇒ current_change 必为 None ⇒ ship_started_at 必为 None）
- [x] Task 6: 写 1 个新 bats integration test tests/integration/test_cleanup_plan_handoff.bats（≥5 cases 锁定新行为）
- [x] Task 7: 写 1 个新 pytest unit test tests/unit/test_cleanup_plan_handoff.py 覆盖 Python 块的 4 个分支
- [x] Task 8: GIVEN plan-handoff.json {active_changes: 1, current_change: "fix-foo"}

### Phase 3: TDD green & verification

- [x] Verify all new tests pass (green)
- [x] Run full unit test suite: `pytest tests/unit/ -q`
- [x] Run integration tests: `bats tests/integration/<new>.bats`
- [x] Verify no regressions in adjacent modules

### Phase 4: Documentation & cleanup

- [ ] Update relevant docstrings/inline comments if API changed
- [ ] Update CHANGELOG if user-facing behavior changed
- [ ] Verify `openspec validate <change>` passes
- [ ] Commit changes with conventional commit message

## Acceptance Verification


## Reference

- Source proposal: `proposal.md`
- Source improvement: `.rddf/improvements/<name>.md`
- Generated by: `guide-plan` Phase 2.5 fill
