#!/usr/bin/env bash
# rdd-planner stage exit: emit .planner-handoff.json with awaiting_builder list
set -euo pipefail

CHANGE_NAME="${1:-}"
PROJECT_ROOT="${PROJECT_ROOT:-$(pwd)}"

if [ -z "$CHANGE_NAME" ]; then
    echo "planner_stage_exit.sh requires <change-name>" >&2
    exit 2
fi

if [ ! -d "openspec/changes/$CHANGE_NAME" ]; then
    echo "openspec/changes/$CHANGE_NAME not found" >&2
    exit 2
fi

PROPOSALS=$(python3 -c "
import json
from pathlib import Path
state = Path('.rddf/state/.planner-state.json')
if state.exists():
    d = json.loads(state.read_text())
    print('\n'.join(d.get('active_projects', [])))
" 2>/dev/null || true)
FEATURES=$(rddf roadmap list-features 2>/dev/null | grep -oE 'feat-[a-zA-Z0-9-]+' | head -10 || true)
CURRENT_SPRINT="sprint-$(date -u +%Y-%m)"
APPROVED=$(rddf status --json 2>/dev/null | python3 -c "import sys, json; d=json.load(sys.stdin); print(sum(1 for c in d.get('changes', []) if c.get('status')=='approved'))" 2>/dev/null || echo "0")
AWAITING="add-$CHANGE_NAME"

# ADR-0048 §Decision 2: read recommended_route from planner-state.json (REQUIRED field).
# Default "unknown" only if state missing; planner-done 双门控会拒绝 exit 如果仍为 unknown.
RECOMMENDED=$(python3 -c "
import json
from pathlib import Path
state = Path('.rddf/state/.planner-state.json')
if state.exists():
    d = json.loads(state.read_text())
    print(d.get('recommended_route', 'unknown'))
else:
    print('unknown')
" 2>/dev/null || echo "unknown")

export PROJECT_ROOT PROPOSALS_READY="$PROPOSALS" PROPOSALS_APPROVED_COUNT="$APPROVED" FEATURES_ACTIVE="$FEATURES" CURRENT_SPRINT AWAITING_BUILDER="$AWAITING" RECOMMENDED_ROUTE="$RECOMMENDED"

# 双门控检查 (per ADR-0048 §Decision 2):
#   门控1: .rddf/roadmap.md 必须存在
#   门控2: recommended_route != "unknown"
if [ ! -f ".rddf/roadmap.md" ] && [ ! -f "roadmap.md" ]; then
    echo "planner-done 双门控失败: 门控1 - .rddf/roadmap.md 不存在" >&2
    echo "  请先完成 rdd-planner Phase 0 roadmap-bootstrap 或 Phase 4 audit/sync" >&2
    exit 2
fi

if [ "$RECOMMENDED" = "unknown" ]; then
    echo "planner-done 双门控失败: 门控2 - recommended_route=unknown" >&2
    echo "  请先运行 rddf planner sync --apply 生成 advisory 信号" >&2
    exit 2
fi

python3 -m _lib.planner_handoff
echo "planner stage exit complete: $AWAITING -> rdd-builder (recommended_route=$RECOMMENDED)"

# Refresh AUTO: objectives sentinel in AGENTS.md (per add-objective-tracking)
# Mirrors the existing AUTO feature fragments / sprint sentinels — same env-var
# pattern (no bash string interpolation). Non-blocking: failures here never
# affect the planner-handoff.json write result.
PROJECT_ROOT="$PROJECT_ROOT" python3 - <<'PYEOF' 2>/dev/null || true
import os, re, sys
from pathlib import Path

PROJECT_ROOT = Path(os.environ.get("PROJECT_ROOT", "."))
sys.path.insert(0, str(PROJECT_ROOT))
try:
    from _lib.objective import parse_objective
except ImportError:
    sys.exit(0)

obj_dir = PROJECT_ROOT / ".rddf" / "roadmap" / "objectives"
agents_md = PROJECT_ROOT / "AGENTS.md"
if not obj_dir.is_dir() or not agents_md.exists():
    sys.exit(0)

rows = []
for f in sorted(obj_dir.glob("*.md")):
    if f.parent.name == "archive":
        continue
    try:
        data = parse_objective(f)
    except (ValueError, OSError):
        continue
    fm = data["frontmatter"]
    rows.append(
        f"| {fm.get('status', '?')} | {fm.get('priority', '?')} "
        f"| {f.stem} | {fm.get('theme', '?')[:80]} |"
    )

SENTINEL_START = "<!-- AUTO: objectives start -->"
SENTINEL_END = "<!-- AUTO: objectives end -->"
text = agents_md.read_text(encoding="utf-8")

new_block = f"{SENTINEL_START}\n"
new_block += "\n### Objectives (auto-generated by rdd-planner)\n\n"
new_block += "| Status | Priority | ID | Theme |\n|---|---|---|---|\n"
if rows:
    new_block += "\n".join(rows) + "\n"
else:
    new_block += "\n_(no active objectives)_\n"
new_block += f"\n{SENTINEL_END}\n"

if SENTINEL_START in text and SENTINEL_END in text:
    text = re.sub(
        rf"{re.escape(SENTINEL_START)}.*?{re.escape(SENTINEL_END)}",
        new_block.rstrip("\n"),
        text,
        flags=re.DOTALL,
    )
else:
    # Append at end if sentinels not yet present
    text = text.rstrip("\n") + "\n\n" + new_block

agents_md.write_text(text, encoding="utf-8")
PYEOF

# ── reflect_engine(plan): post-stage-exit reflection hook ──
# Non-blocking: failures here never affect the planner-handoff.json write result.
# Mirrors skills/rdd-arch/scripts/write_arch_handoff.sh:48-66 and
# _lib/archive.sh:642-670 (both wired per ADR-0027 §1.0). Plan phase
# thresholds: same gate+error >=2 OR any unrecovered_failure → propose_issue.
# Reads event_log.json last 20 events filtered to unrecovered_failure/execute_error
# (same pattern as ship hook — arch hook is log-only with empty failures).
if [ "${SKIP_WORKFLOW_REFLECTION:-}" != "1" ]; then
    PROJECT_ROOT="$PROJECT_ROOT" python3 -c "
import os, sys, json
root = os.environ.get('PROJECT_ROOT', '.')
sys.path.insert(0, root)
try:
    from skills._lib.reflect_engine import ReflectEngine
    failures = []
    event_log_path = os.path.join(root, '.rddf', 'state', 'event_log.json')
    if os.path.isfile(event_log_path):
        with open(event_log_path) as f:
            events = json.load(f)
        for ev in events[-20:]:
            if ev.get('type') in ('unrecovered_failure', 'execute_error'):
                failures.append(ev)
    engine = ReflectEngine(phase='plan', project_root=root, timeout=10)
    result = engine.analyze(failures=failures)
    if result.action == 'propose_issue':
        print(f'🔍 Reflect: Plan phase detected failures.')
        print(f'   Fingerprint: {result.fingerprint}')
except Exception:
    pass  # non-blocking
" 2>/dev/null || true
fi