# skills/_lib/reflect_engine.py
"""Workflow reflection engine - analyzes failures and proposes GitHub issues.

Read-only analysis, non-blocking gate hook. Called from arch-done, plan-done,
and ship-archive gates as a post-processing step.

Design: ADR-0003 (three-phase), ADR-0007 (gate), ADR-0017 (session)
"""

import os
import re
import time
import json
import logging
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

from skills._lib.reflect_cooldown import CooldownManager
from skills._lib.reflect_dedup import DedupMatcher

logger = logging.getLogger(__name__)


@dataclass
class ReflectResult:
    """Result of reflection analysis."""
    action: str  # "none", "propose_issue", "log_friction", "skipped", "error"
    fingerprint: str = ""
    session_id: str = ""
    errors: list = field(default_factory=list)
    matched_improvement: Optional[dict] = None
    reason: str = ""


@dataclass
class IssueDraft:
    """Draft issue to be confirmed by user before filing."""
    title: str
    body: str
    target_repo: str
    labels: list = field(default_factory=list)


class ReflectEngine:
    """Reflection engine that analyzes workflow failures and manages issue lifecycle.

    Phases:
      arch  -> log-only (friction signals to .rddf/state/reflect-friction.log)
      plan  -> trigger when same root cause >=2 failures
      ship  -> trigger on any unrecovered failure (max_retries exhausted, gate error)
    """

    def __init__(self, phase, project_root=None, dry_run=False, timeout=10.0):
        if phase not in ("arch", "plan", "ship"):
            raise ValueError(f"Invalid phase: {phase}. Must be arch, plan, or ship.")
        self.phase = phase
        self.project_root = project_root or self._find_project_root()
        self.dry_run = dry_run
        self.timeout = timeout
        self.cooldown = CooldownManager(
            cooldown_file=os.path.join(self.project_root, ".rddf", "state", "reflect-cooldown.json")
        )
        self.dedup = DedupMatcher(project_root=self.project_root)

    @staticmethod
    def _find_project_root():
        """Find the project root by looking for .git directory."""
        current = Path.cwd()
        for parent in [current] + list(current.parents):
            if (parent / ".git").exists():
                return str(parent)
        return str(current)

    # ─── Public API ───────────────────────────────────────────────

    def analyze(self, failures):
        """Analyze failures and return a ReflectResult.

        Args:
            failures: list of dicts with keys: type, error, gate, step, retry, max_retries
        """
        if os.environ.get("SKIP_WORKFLOW_REFLECTION") == "1":
            return ReflectResult(action="skipped", reason="SKIP_WORKFLOW_REFLECTION=1")

        try:
            return self._do_analyze(failures)
        except TimeoutError as e:
            logger.error("reflect_engine analyze timed out: %s", e)
            return ReflectResult(action="error", reason=f"timeout: {e}")
        except Exception as e:
            logger.error("reflect_engine analyze failed: %s", e)
            return ReflectResult(action="error", reason=f"engine error: {e}")

    def draft_issue(self, result):
        """Create an IssueDraft from a ReflectResult."""
        phase_display = {"arch": "Architecture (arch)", "plan": "Planning (plan)", "ship": "Ship (ship)"}
        title = f"[reflect] {self.phase}: {result.fingerprint}"
        body = f"""## Reflection Analysis

**Phase:** {phase_display.get(self.phase, self.phase)}
**Session ID:** {result.session_id}
**Fingerprint:** `{result.fingerprint}`
**Timestamp:** {time.strftime('%Y-%m-%d %H:%M:%S UTC', time.gmtime())}

### Errors Detected
"""
        for i, err in enumerate(result.errors[-5:], 1):  # Last 5 errors max
            body += f"{i}. {err}\n"

        body += """
---
*Auto-generated by reflect_engine.py. See [ADR-0024](docs/adr/ADR-0024-deps-driven-execution-mode.md) for context.*
"""
        target = self._route_issue(result.errors)
        return IssueDraft(title=title, body=body, target_repo=target,
                          labels=["auto-reflect", self.phase])

    # ─── Internal ────────────────────────────────────────────────

    def _do_analyze(self, failures):
        """Core analysis logic. May raise TimeoutError to signal timeout."""
        if not failures:
            return ReflectResult(action="none")

        # Determine gate_name from first failure
        first = failures[0]
        gate_name = first.get("gate", first.get("step", "unknown"))
        error_cat = self._classify_error(first.get("error", "unknown"))
        eff_phase = self._derive_phase(failures)
        fingerprint = self._make_fingerprint(eff_phase, gate_name, error_cat)

        if self.phase == "arch":
            self._log_friction(fingerprint, failures)
            return ReflectResult(action="log_friction", fingerprint=fingerprint)

        if self.cooldown.is_cooling(fingerprint):
            return ReflectResult(action="none", fingerprint=fingerprint,
                                 reason="within cooldown window")

        if not self._meets_threshold(failures):
            return ReflectResult(action="none", fingerprint=fingerprint)

        # Dedup check
        matched = self.dedup.check_all(fingerprint)
        if matched:
            return ReflectResult(action="matched", fingerprint=fingerprint,
                                 matched_improvement=matched,
                                 reason=f"already in {matched['source']}: {matched['matched_name']}")

        # Record cooldown
        self.cooldown.record(fingerprint)

        return ReflectResult(
            action="propose_issue",
            fingerprint=fingerprint,
            session_id=self._get_session_id(),
            errors=[f.get("error", str(f)) for f in failures[-3:]],
        )

    def _meets_threshold(self, failures):
        """Check if failures meet the per-phase threshold.

        Thresholds are driven by failure type, not the engine's configured phase:
          - any unrecovered_failure / gate_error -> ship semantics (always trigger)
          - repeated gate_fail with same root cause (>=2) -> plan semantics
        """
        if any(f.get("type") in ("unrecovered_failure", "gate_error") for f in failures):
            return True
        error_counts = {}
        for f in failures:
            key = f.get("gate", "") + ":" + f.get("error", "")
            error_counts[key] = error_counts.get(key, 0) + 1
        return any(c >= 2 for c in error_counts.values())

    def _derive_phase(self, failures):
        """Derive the fingerprint phase from failure types rather than engine config.

        unrecovered_failure / gate_error -> "ship"; arch stays "arch"; else engine phase.
        """
        if self.phase == "arch":
            return "arch"
        if any(f.get("type") in ("unrecovered_failure", "gate_error") for f in failures):
            return "ship"
        return self.phase

    def _make_fingerprint(self, phase, gate_name, error_category):
        """Create fingerprint: {phase}:{gate_name}:{error_category} (sanitized).

        Sanitization: lowercase, spaces->hyphens, underscores->hyphens,
        strip non [a-z0-9-] chars, truncate to 50 chars, trim leading/trailing hyphens.
        """
        cat = re.sub(r'[^a-z0-9-]', '',
                     error_category.lower().replace(' ', '-').replace('_', '-'))
        cat = cat[:50].strip('-')
        gate = re.sub(r'[^a-z0-9-]', '',
                      gate_name.lower().replace(' ', '-').replace('_', '-'))
        return f"{phase}:{gate}:{cat}"

    def _classify_error(self, error_str):
        """Classify an error string into a category for fingerprinting."""
        error_lower = error_str.lower()
        if "timeout" in error_lower:
            return "timeout"
        if "gate" in error_lower or "quality" in error_lower:
            return "quality-gate-fail"
        if "import" in error_lower or "module" in error_lower:
            return "import-error"
        if "permission" in error_lower or "denied" in error_lower:
            return "permission-error"
        return "general-error"

    def _route_issue(self, errors):
        """Determine target repo based on affected paths.

        Rules:
          - skills/_lib/ or docs/adr/ paths -> chisuhua/rdd-workflow
          - all other paths -> git remote origin (subprocess, then .git/config parse)
        """
        for err in errors:
            err_str = str(err)
            if "skills/_lib/" in err_str or "docs/adr/" in err_str:
                return "chisuhua/rdd-workflow"
        url = self._git_remote_origin()
        if url:
            match = re.search(r'[:/]([^/]+/[^/]+?)(?:\.git)?$', url)
            if match:
                return match.group(1)
        return "unknown/unknown"

    def _git_remote_origin(self):
        """Get origin remote URL via git CLI, falling back to parsing .git/config."""
        try:
            import subprocess
            result = subprocess.run(
                ["git", "remote", "get-url", "origin"],
                capture_output=True, text=True, cwd=self.project_root, timeout=5
            )
            if result.returncode == 0 and result.stdout.strip():
                return result.stdout.strip()
        except Exception:
            pass
        config_path = os.path.join(self.project_root, ".git", "config")
        try:
            if os.path.isfile(config_path):
                with open(config_path) as f:
                    config = f.read()
                match = re.search(r'\[remote "origin"\].*?\burl\s*=\s*(\S+)',
                                  config, re.DOTALL)
                if match:
                    return match.group(1).strip()
        except Exception:
            pass
        return None

    def _get_session_id(self):
        """Get current rddf-session ID from sessions.json."""
        try:
            sessions_file = os.path.join(self.project_root, ".rddf", "state", "sessions.json")
            if os.path.isfile(sessions_file):
                with open(sessions_file) as f:
                    data = json.load(f)
                sessions = data.get("sessions", [])
                active = [s for s in sessions if s.get("state") == "active"]
                if active:
                    return active[-1].get("session_id", "unknown")
        except Exception:
            pass
        return "unknown"

    def _log_friction(self, fingerprint, failures):
        """Log friction signal to .rddf/state/reflect-friction.log (arch phase only)."""
        log_file = os.path.join(self.project_root, ".rddf", "state", "reflect-friction.log")
        os.makedirs(os.path.dirname(log_file), exist_ok=True)
        with open(log_file, 'a') as f:
            f.write(f"[{time.strftime('%Y-%m-%dT%H:%M:%S')}] {fingerprint}\n")
            for err in failures[-3:]:
                f.write(f"  {err.get('error', str(err))}\n")
            f.write("\n")
